#  ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
#  ║ ███████╗░█████╗░░█████╗░███╗░░██╗░█████╗░███╗░░░███╗██╗░░░██╗██████╗░██╗░░░░░██╗░░░██╗░██████╗ ║
#  ║ ██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗████╗░████║╚██╗░██╔╝██╔══██╗██║░░░░░██║░░░██║██╔════╝ ║
#  ║ █████╗░░██║░░╚═╝██║░░██║██╔██╗██║██║░░██║██╔████╔██║░╚████╔╝░██████╔╝██║░░░░░██║░░░██║╚█████╗░ ║
#  ║ ██╔══╝░░██║░░██╗██║░░██║██║╚████║██║░░██║██║╚██╔╝██║░░╚██╔╝░░██╔═══╝░██║░░░░░██║░░░██║░╚═══██╗ ║
#  ║ ███████╗╚█████╔╝╚█████╔╝██║░╚███║╚█████╔╝██║░╚═╝░██║░░░██║░░░██║░░░░░███████╗╚██████╔╝██████╔╝ ║
#  ║ ╚══════╝░╚════╝░░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝░░░░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚══════╝░╚═════╝░╚═════╝░ ║
#  ╚════════════════════════════════════════════════════════════════════════════════════════════════╝

# EconomyPlus made by _ItsWagPvP
# Watch the full resource on https://github.com/ItsWagPvP/EconomyPlus

# Do not change this
Version: ${project.version}

Updater:
  Console: true
  Player: true

# Used to format the %economyplus_money_formatted% placeholder
# 1000 = 1k
# 1000000 = 1M
# 1000000000 = 1B
# 1000000000000 = 1T
# 1000000000000000 = 1Q
Format:
  k: "k"
  M: "M"
  B: "B"
  T: "T"
  Q: "Q"
